server {
    listen ${FOLIO_PORT};
    root ${FOLIO_APPDIR}/app;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # proxy requests from /_* to the internal server port
    location ~ ^/_ {
        proxy_pass http://localhost:${FOLIO_SERVER_PORT};
    }

    # static assets
    location ~* ^(?!/_).*\.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|map)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # spa fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
