[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:folio_server]
directory=${FOLIO_APPDIR}
command=node folio.js start --port ${FOLIO_SERVER_PORT}
autorestart=true
user=node
