[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:folio]
directory=/opt/folio
command=node folio.js start --port 3000
autorestart=true
user=node
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

