export const getDefaultState = () => ({
    snapshot: null,
    style: {},
    selection: null,
    activeTool: null,
    activeAction: null,
    activeElement: null,
    activeGroup: null,
    activeDialog: null,
    zoom: 1,
    translateX: 0,
    translateY: 0,
    lastTranslateX: 0,
    lastTranslateY: 0,
    isDragged: false,
    isResized: false,
    isPrevSelected: false,
    showSettings: false,
    showExport: false,
    showMenu: false,
    grid: true,
    background: "#fafafa",
});
