export default {
    "editor": "text-neutral-900",

    "button.primary": "bg-neutral-950 hover:bg-neutral-900 text-white text-sm",
    "button.secondary": "bg-white text-neutral-900 hover:bg-neutral-200 border border-neutral-200 text-sm",

    "context-menu": "bg-white shadow-sm border border-neutral-200",
    "context-menu.item": "hover:bg-neutral-200",
    "context-menu.separator": "bg-neutral-200",

    "dialog": "bg-white border border-neutral-200 shadow-sm",
    "dialog.body": "",
    "dialog.close": "text-neutral-700 hover:text-neutral-900",
    "dialog.description": "text-sm text-neutral-800",
    "dialog.footer": "",
    "dialog.header": "",
    "dialog.title": "font-bold text-lg text-neutral-950",

    "dropdown": "bg-white border border-neutral-200 shadow-sm",
    "dropdown.item": "hover:bg-neutral-200",
    "dropdown.label": "text-neutral-600",
    "dropdown.separator": "bg-neutral-200",

    "export.preview": "text-neutral-500 border border-neutral-200",

    "form": "",
    "form.checkbox": "",
    "form.checkbox.title": "text-neutral-900",
    "form.checkbox.input": "",
    "form.checkbox.input.active": "bg-neutral-900 border-neutral-900",
    "form.checkbox.input.inactive": "bg-neutral-200 border-neutral-200",
    "form.colorpicker.preview": "border border-neutral-200",
    "form.colorpicker.input": "bg-white border border-neutral-200 text-neutral-900",
    "form.colorpicker.palette.item": "border border-neutral-200",
    "form.fontpicker.item.active": "bg-neutral-900 text-white",
    "form.fontpicker.item.inactive": "text-neutral-900 bg-neutral-100 hover:bg-neutral-200",
    "form.select.item.active": "bg-neutral-900 text-white",
    "form.select.item.inactive": "bg-neutral-100 hover:bg-neutral-200",
    "form.colorselect.item.active": "border border-neutral-300",
    "form.colorselect.item.inactive": "border border-neutral-300 opacity-50 hover:opacity-100",
    "form.imageselect": "",
    "form.imageselect.item.active": "border border-neutral-900",
    "form.imageselect.item.inactive": "border border-neutral-200 hover:bg-neutral-200",
    "form.labeledselect.item.active": "bg-neutral-900 text-white",
    "form.labeledselect.item.inactive": "bg-neutral-100 hover:bg-neutral-200",
    "form.option": "text-neutral-900",
    "form.option.title": "font-medium",
    "form.option.helper": "text-neutral-600",
    "form.range": "",
    "form.range.title": "text-neutral-900",
    "form.range.input": "bg-neutral-200",
    "form.separator": "bg-neutral-200",
    "form.text.input": "bg-white border border-neutral-200 text-neutral-900",

    "hint": "",
    "hint.content": "",
    "hint.content.description": "text-neutral-500",
    "hint.content.title": "text-neutral-600",
    "hint.icon": "text-neutral-600",

    "island": "shadow-sm bg-white border border-neutral-200",
    "island.item": "hover:bg-neutral-200 text-neutral-900 group-focus-within:bg-neutral-200",
    "island.item.active": "bg-neutral-200 text-neutral-950",
    "island.separator": "bg-neutral-200",

    "layers": "",
    "layers.empty": "text-neutral-600",
    "layers.item": "hover:bg-neutral-200",
    "layers.item.action": "text-neutral-500 hover:text-neutral-900",
    "layers.item.name": "text-neutral-900",
    "layers.item.preview": "border border-neutral-300 bg-white",

    "libraries.item.action": "text-neutral-500 hover:text-neutral-900",
    "libraries.item.empty": "text-neutral-800 bg-neutral-100",

    "pages": "",
    "pages.item": "hover:bg-neutral-200",
    "pages.item.action": "text-neutral-500 hover:text-neutral-900",
    "pages.gallery.item": "border-2 border-neutral-200",
    "pages.gallery.item.active": "border-neutral-950",

    "panel": "border border-neutral-200 shadow-sm bg-white",
    "panel.body": "",
    "panel.header": "border-b border-neutral-200",
    "panel.header.button": "",
    "panel.header.button.active": "bg-neutral-900 text-white",
    "panel.header.button.inactive": "hover:bg-neutral-200 ",
    "panel.header.title": "font-bold",
    "panel.separator": "bg-neutral-200",
    // "panel.tabs": "bg-neutral-100",
    // "panel.tabs.item.inactive": "text-neutral-900 hover:bg-neutral-200",
    // "panel.tabs.item.active": "text-white bg-neutral-900",

    "title.input": "text-neutral-900 bg-neutral-200",
    "title.preview": "text-neutral-900 hover:bg-neutral-200",

    "toolbar": "border border-neutral-200 bg-white shadow-sm text-neutral-900",
    "toolbar.button": "",
    "toolbar.button.inactive": "hover:bg-neutral-200",
    "toolbar.button.active": "bg-neutral-950 text-white",
    "toolbar.dots": "hover:bg-neutral-200 group-focus-within:bg-neutral-200",
    "toolbar.pick": "bg-white border border-neutral-200 shadow-sm",
    "toolbar.pick.separator": "bg-neutral-200",
    "toolbar.lock.active": "bg-neutral-950 text-white",
    "toolbar.lock.inactive": "opacity-50 hover:opacity-100",
    "toolbar.separator": "bg-neutral-200",

    "welcome": "bg-white border border-neutral-200 shadow-sm",
    "welcome.description": "",
    "welcome.feature": "bg-neutral-50 text-neutral-700",
    "welcome.feature.description": "",
    "welcome.feature.icon": "",
    "welcome.feature.title": "",
    "welcome.title": "text-neutral-950",
    "welcome.version": "text-neutral-400",

};
