// @description check if the provided event.target is related to an input element
export const isInputTarget = event => {
    return event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement;
};

// @description check if the event has been generated by touch or pen
// @url https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType
export const isTouchOrPenEvent = event => {
    return event.pointerType !== "mouse";
};

// @description prevent the default event behavior
export const preventDefault = event => event?.preventDefault?.();

// @description stop the event propagation of the provided event
export const stopEventPropagation = event => event?.stopPropagation?.();
