events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        # root /opt/folio/public;
        index index.html;

        gzip on;
        gzip_types text/plain text/css application/javascript application/json image/svg+xml;
        gzip_min_length 1024;

        # proxy requests from /_auth to the internal authentication service
        location /_auth/ {
            proxy_pass http://localhost:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # proxy requests from /_storage to the internal storage service
        location /_storage/ {
            proxy_pass http://localhost:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # static assets
        location ~* ^(?!/_).*\.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|map)$ {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            try_files $uri =404;
        }

        # spa fallback
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
