[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:folio_auth]
directory=/opt/folio
command=node folio.js start:auth --port 3001
autorestart=true
user=node
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:folio_storage]
directory=/opt/folio
command=node folio.js start:storage --port 3002
autorestart=true
user=node
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
