export default {
    "editor": "text-gray-900",

    "context-menu": "bg-white shadow-sm border-1 border-gray-200",
    "context-menu.item": "hover:bg-gray-200",
    "context-menu.separator": "bg-gray-200",

    "dialog": "bg-white border-1 border-gray-200 shadow-sm",
    "dialog.body": "",
    "dialog.close": "text-gray-700 hover:text-gray-900",
    "dialog.description": "text-sm text-gray-800",
    "dialog.footer": "",
    "dialog.header": "",
    "dialog.title": "font-bold text-lg text-gray-950",

    "export.preview": "text-gray-500 border-1 border-gray-200",

    "form": "",
    "form.checkbox": "",
    "form.checkbox.title": "text-gray-900",
    "form.checkbox.input": "",
    "form.checkbox.input.active": "bg-gray-900 border-gray-900",
    "form.checkbox.input.inactive": "bg-gray-200 border-gray-200",
    "form.colorpicker.preview": "border-1 border-gray-200",
    "form.colorpicker.input": "bg-white border-1 border-gray-200 text-gray-900",
    "form.colorpicker.palette.item": "border-1 border-gray-200",
    "form.select.item.active": "bg-gray-900 text-white",
    "form.select.item.inactive": "bg-gray-100 hover:bg-gray-200",
    "form.colorselect.item.active": "border-1 border-gray-300",
    "form.colorselect.item.inactive": "border-1 border-gray-300 opacity-50 hover:opacity-100",
    "form.imageselect": "",
    "form.imageselect.item.active": "border-1 border-gray-900",
    "form.imageselect.item.inactive": "border-1 border-gray-200 hover:bg-gray-200",
    "form.labeledselect.item.active": "bg-gray-900 text-white",
    "form.labeledselect.item.inactive": "bg-gray-100 hover:bg-gray-200",
    "form.option": "text-gray-900",
    "form.option.title": "font-medium",
    "form.option.helper": "text-gray-600",
    "form.range": "",
    "form.range.title": "text-gray-900",
    "form.range.input": "bg-gray-200",
    "form.separator": "bg-gray-200",
    "form.text.input": "bg-white border-1 border-gray-200 text-gray-900",

    "hint": "",
    "hint.content": "",
    "hint.content.description": "text-gray-500",
    "hint.content.title": "text-gray-600",
    "hint.icon": "text-gray-600",

    "island": "shadow-sm bg-white border-1 border-gray-200",
    "island.item": "hover:bg-gray-200 text-gray-900 group-focus-within:bg-gray-200",
    "island.item.active": "bg-gray-200 text-gray-950",
    "island.separator": "bg-gray-200",

    "layers": "",
    "layers.empty": "text-gray-600",
    "layers.item": "hover:bg-gray-200",
    "layers.item.action": "text-gray-500 hover:text-gray-900",
    "layers.item.name": "text-gray-900",
    "layers.item.preview": "border-1 border-gray-300 bg-white",

    "libraries.item.action": "text-gray-500 hover:text-gray-900",
    "libraries.item.empty": "text-gray-800 bg-gray-100",

    "pages": "",
    "pages.item": "hover:bg-gray-200",
    "pages.item.action": "text-gray-500 hover:text-gray-900",
    "pages.gallery.item": "border-2 border-gray-200",
    "pages.gallery.item.active": "border-gray-950",

    "panel": "border-1 border-gray-200 shadow-sm bg-white",
    "panel.body": "",
    "panel.header": "border-b-1 border-gray-200",
    "panel.header.button": "",
    "panel.header.button.active": "bg-gray-900 text-white",
    "panel.header.button.inactive": "hover:bg-gray-200 ",
    "panel.header.title": "font-bold",
    "panel.separator": "bg-gray-200",
    // "panel.tabs": "bg-gray-100",
    // "panel.tabs.item.inactive": "text-gray-900 hover:bg-gray-200",
    // "panel.tabs.item.active": "text-white bg-gray-900",

    "title.input": "text-gray-900 bg-gray-200",
    "title.preview": "text-gray-900 hover:bg-gray-200",

    "toolbar": "border-1 border-gray-200 bg-white shadow-sm text-gray-900",
    "toolbar.button": "",
    "toolbar.button.inactive": "hover:bg-gray-200",
    "toolbar.button.active": "bg-gray-950 text-white",
    "toolbar.dots": "hover:bg-gray-200 group-focus-within:bg-gray-200",
    "toolbar.pick": "bg-white border-1 border-gray-200 shadow-sm",
    "toolbar.pick.separator": "bg-gray-200",
    "toolbar.lock.active": "bg-gray-950 text-white",
    "toolbar.lock.inactive": "opacity-50 hover:opacity-100",
    "toolbar.separator": "bg-gray-200",

    "welcome": "bg-white border-1 border-gray-200 shadow-sm",
    "welcome.description": "",
    "welcome.feature": "bg-gray-50 text-gray-700",
    "welcome.feature.description": "",
    "welcome.feature.icon": "",
    "welcome.feature.title": "",
    "welcome.title": "text-gray-950",
    "welcome.version": "text-gray-400",

};
