name: docker

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
    paths:
      - apps/studio/Dockerfile
      - .github/workflows/docker.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: ${{ github.repository == 'jmjuanes/folio' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        app: [studio]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/folio-${{ matrix.app }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr,prefix=pr-
            type=semver,pattern={{version}}
            type=raw,value=dev,enable={{is_default_branch}}

      - uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
